-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:24c4f00db1a520901b603b6d8867fa03$
-- 

return {
	texture = 'NewsReader.png',
	frames = {
			{
				name = "Reader_0001_Layer-64.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.0078125, v0 = 0.00390625, u1 = 0.0742188, v1 = 0.0996094 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0002_Layer-63.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.0820312, v0 = 0.00390625, u1 = 0.148438, v1 = 0.0996094 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0003_Layer-62.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.15625, v0 = 0.00390625, u1 = 0.222656, v1 = 0.0996094 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0004_Layer-61.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.230469, v0 = 0.00390625, u1 = 0.296875, v1 = 0.0996094 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0005_Layer-60.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.304688, v0 = 0.00390625, u1 = 0.371094, v1 = 0.0996094 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0006_Layer-59.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.378906, v0 = 0.00390625, u1 = 0.445312, v1 = 0.0996094 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0007_Layer-58.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.453125, v0 = 0.00390625, u1 = 0.519531, v1 = 0.0996094 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0008_Layer-57.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.527344, v0 = 0.00390625, u1 = 0.59375, v1 = 0.0996094 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0009_Layer-56.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.601562, v0 = 0.00390625, u1 = 0.667969, v1 = 0.0996094 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0010_Layer-55.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.675781, v0 = 0.00390625, u1 = 0.742188, v1 = 0.0996094 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0011_Layer-54.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.75, v0 = 0.00390625, u1 = 0.816406, v1 = 0.0996094 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0012_Layer-53.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.824219, v0 = 0.00390625, u1 = 0.890625, v1 = 0.0996094 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0013_Layer-52.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.898438, v0 = 0.00390625, u1 = 0.964844, v1 = 0.0996094 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0014_Layer-51.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.0078125, v0 = 0.103516, u1 = 0.0742188, v1 = 0.199219 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0015_Layer-50.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.0820312, v0 = 0.103516, u1 = 0.148438, v1 = 0.199219 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0016_Layer-49.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.15625, v0 = 0.103516, u1 = 0.222656, v1 = 0.199219 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0017_Layer-48.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.230469, v0 = 0.103516, u1 = 0.296875, v1 = 0.199219 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0018_Layer-47.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.304688, v0 = 0.103516, u1 = 0.371094, v1 = 0.199219 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0019_Layer-46.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.378906, v0 = 0.103516, u1 = 0.445312, v1 = 0.199219 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0020_Layer-45.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.453125, v0 = 0.103516, u1 = 0.519531, v1 = 0.199219 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0021_Layer-44.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.527344, v0 = 0.103516, u1 = 0.59375, v1 = 0.199219 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0022_Layer-43.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.601562, v0 = 0.103516, u1 = 0.667969, v1 = 0.199219 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0023_Layer-42.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.675781, v0 = 0.103516, u1 = 0.742188, v1 = 0.199219 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0024_Layer-41.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.75, v0 = 0.103516, u1 = 0.816406, v1 = 0.199219 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0025_Layer-40.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.824219, v0 = 0.103516, u1 = 0.890625, v1 = 0.199219 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0026_Layer-39.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.898438, v0 = 0.103516, u1 = 0.964844, v1 = 0.199219 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0027_Layer-38.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.0078125, v0 = 0.203125, u1 = 0.0742188, v1 = 0.298828 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0028_Layer-37.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.0820312, v0 = 0.203125, u1 = 0.148438, v1 = 0.298828 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0029_Layer-36.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.15625, v0 = 0.203125, u1 = 0.222656, v1 = 0.298828 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0030_Layer-35.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.230469, v0 = 0.203125, u1 = 0.296875, v1 = 0.298828 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0031_Layer-34.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.304688, v0 = 0.203125, u1 = 0.371094, v1 = 0.298828 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0032_Layer-33.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.378906, v0 = 0.203125, u1 = 0.445312, v1 = 0.298828 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0033_Layer-32.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.378906, v0 = 0.203125, u1 = 0.445312, v1 = 0.298828 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0034_Layer-31.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.453125, v0 = 0.203125, u1 = 0.519531, v1 = 0.298828 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0035_Layer-30.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.527344, v0 = 0.203125, u1 = 0.59375, v1 = 0.298828 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0036_Layer-29.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.601562, v0 = 0.203125, u1 = 0.667969, v1 = 0.298828 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0037_Layer-28.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.675781, v0 = 0.203125, u1 = 0.742188, v1 = 0.298828 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0038_Layer-27.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.75, v0 = 0.203125, u1 = 0.816406, v1 = 0.298828 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0039_Layer-26.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.824219, v0 = 0.203125, u1 = 0.890625, v1 = 0.298828 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0040_Layer-25.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.898438, v0 = 0.203125, u1 = 0.964844, v1 = 0.298828 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0041_Layer-24.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.0078125, v0 = 0.302734, u1 = 0.0742188, v1 = 0.398438 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0042_Layer-23.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.0820312, v0 = 0.302734, u1 = 0.148438, v1 = 0.398438 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0043_Layer-22.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.15625, v0 = 0.302734, u1 = 0.222656, v1 = 0.398438 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0044_Layer-21.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.230469, v0 = 0.302734, u1 = 0.296875, v1 = 0.398438 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0045_Layer-20.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.304688, v0 = 0.302734, u1 = 0.371094, v1 = 0.398438 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0046_Layer-19.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.378906, v0 = 0.302734, u1 = 0.445312, v1 = 0.398438 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0047_Layer-18.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.453125, v0 = 0.302734, u1 = 0.519531, v1 = 0.398438 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0048_Layer-17.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.527344, v0 = 0.302734, u1 = 0.59375, v1 = 0.398438 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0049_Layer-16.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.601562, v0 = 0.302734, u1 = 0.667969, v1 = 0.398438 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0050_Layer-15.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.675781, v0 = 0.302734, u1 = 0.742188, v1 = 0.398438 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0051_Layer-14.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.75, v0 = 0.302734, u1 = 0.816406, v1 = 0.398438 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0052_Layer-13.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.824219, v0 = 0.302734, u1 = 0.890625, v1 = 0.398438 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0053_Layer-12.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.898438, v0 = 0.302734, u1 = 0.964844, v1 = 0.398438 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0054_Layer-11.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.0078125, v0 = 0.402344, u1 = 0.0742188, v1 = 0.498047 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0055_Layer-10.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.0820312, v0 = 0.402344, u1 = 0.148438, v1 = 0.498047 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0056_Layer-9.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.15625, v0 = 0.402344, u1 = 0.222656, v1 = 0.498047 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0057_Layer-8.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.230469, v0 = 0.402344, u1 = 0.296875, v1 = 0.498047 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0058_Layer-7.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.304688, v0 = 0.402344, u1 = 0.371094, v1 = 0.498047 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0059_Layer-6.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.378906, v0 = 0.402344, u1 = 0.445312, v1 = 0.498047 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0060_Layer-5.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.453125, v0 = 0.402344, u1 = 0.519531, v1 = 0.498047 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0061_Layer-4.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.527344, v0 = 0.402344, u1 = 0.59375, v1 = 0.498047 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0062_Layer-3.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.601562, v0 = 0.402344, u1 = 0.667969, v1 = 0.498047 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0063_Layer-2.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.675781, v0 = 0.402344, u1 = 0.742188, v1 = 0.498047 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Reader_0064_Layer-1.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 49 },
				uvRect = { u0 = 0.75, v0 = 0.402344, u1 = 0.816406, v1 = 0.498047 },
				spriteSourceSize = { width = 17, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

